import type { Metadata } from "next";
// import { sahel } from 'next-persian-fonts/sahel'
// import { vazirMatn } from 'next-persian-fonts/vazirmatn'
import { estedad, estedadFD } from 'next-persian-fonts/estedad'
import "../globals.css";
import Layout from "@/components/Layout/Layout";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={estedadFD.className}
      >
        <ThemeProvider attribute="class">
          <Layout>
            {children}
          </Layout>
        </ThemeProvider>

        <div id="modal-portal"></div>
        <div id="modal-portal"></div>
        <div id="dialog-portal"></div>
        <div id="toasts-portal"></div>

      </body>
    </html>
  );
}
