import type { Metadata } from "next";
// import { sahel } from 'next-persian-fonts/sahel'
// import { vazirMatn } from 'next-persian-fonts/vazirmatn'
import { estedadFD } from 'next-persian-fonts/estedad'
import "../globals.css";
import Layout from "@/components/Auth/Layout/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={estedadFD.className}
      >
        <Layout>
          {children}
        </Layout>

        <div id="toasts-portal"></div>
      </body>
    </html>
  );
}
