import type { Metadata } from "next";
// import { sahel } from 'next-persian-fonts/sahel'
// import { vazirMatn } from 'next-persian-fonts/vazirmatn'
import { estedadFD } from 'next-persian-fonts/estedad'
import "../globals.css";
import { ThemeProvider } from "next-themes";
import DashboardLayout from "@/components/Layout/DashboardLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={`${estedadFD.className} relative`}
      >
        <ThemeProvider attribute="class">
          <DashboardLayout>
            {children}
          </DashboardLayout>
        </ThemeProvider>

        <div id="modal-portal"></div>
        <div id="dialog-portal"></div>
        <div id="toasts-portal"></div>
      </body>
    </html>
  );
}
